scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets: ['docker.for.mac.localhost:3000', 'cadvisor:8080', ]
  
  ## config for the multiple Redis targets that the exporter will scrape
  #target will be queried with this web request: http://docker.for.mac.localhos:9121/scrape?target=first-redis-host:6379
- job_name: 'redis_exporter_targets'
  static_configs:
    - targets:
      - redis://127.0.0.1:6379
      - redis://127.0.0.1:6380
  metrics_path: /scrape
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: docker.for.mac.localhost:9121
- job_name: 'redis_exporter'
  static_configs:
    - targets: ['docker.for.mac.localhost:9121']